output:
  format: "json" # Maybe add option for pickle?
  dir: "./output/"
  file: "output-{concurrency:03d}.json"
storage: # TODO
  type: local
dataset:
  file: "datasets/openorca_large_subset_011.jsonl"
  max_queries: 4000
  min_input_tokens: 0
  max_input_tokens: 1024
  min_output_tokens: 0
  max_output_tokens: 512
  max_sequence_tokens: 2048
load_options:
  type: rps #Options: concurrency, rps, loadgen, stair-step
  concurrency: 4 
  rps: 2 
  duration: 20 # In seconds. Maybe in future support "100s" "10m", etc...
plugin: "openai_plugin"
plugin_options:
  load_balance: False
  use_tls: False # Use True if querying an SSL grpc endpoint over https
  streaming: True
  # port: 8033 # Some plugins like the standalone TGIS plugin need port
  model_name: "flan-t5-small"
  host: "http://route.to.host"
  endpoint: "/v1/completions"
extra_metadata:
  replicas: 1
