output:
  format: "json" # Maybe add option for pickle?
  dir: "./output/"
  file: "output.json"
warmup: false
storage: # TODO
  type: local
dataset:
  file: "datasets/openorca_large_subset_010.jsonl"
  max_queries: 1000
  max_input_tokens: 1024
  max_output_tokens: 256
load_options:
  type: constant #Future options: loadgen, stair-step
  concurrency: 4
  duration: 20 # In seconds. Maybe in future support "100s" "10m", etc...
plugin: "caikit_client_plugin"
plugin_options:
  interface: "http" # Some plugins like caikit-nlp-client should support grpc/http
  streaming: True
  model_name: "model-70b-chat"
  route: "https://route.to.host"
extra_metadata:
  replicas: 1
